// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package net

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a975c40DecodeFinnflareComDctBackendNet(in *jlexer.Lexer, out *ResponseBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "error":
			out.Error = bool(in.Bool())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				if out.Data == nil {
					out.Data = new(Data)
				}
				(*out.Data).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet(out *jwriter.Writer, in ResponseBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.Bool(bool(in.Error))
	}
	if in.Data != nil {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		(*in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet(l, v)
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet1(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
				out.Header = nil
			} else {
				if out.Header == nil {
					out.Header = new(Header)
				}
				(*out.Header).UnmarshalEasyJSON(in)
			}
		case "request":
			if in.IsNull() {
				in.Skip()
				out.RequestBody = nil
			} else {
				if out.RequestBody == nil {
					out.RequestBody = new(Body)
				}
				(*out.RequestBody).UnmarshalEasyJSON(in)
			}
		case "response":
			if in.IsNull() {
				in.Skip()
				out.ResponseBody = nil
			} else {
				if out.ResponseBody == nil {
					out.ResponseBody = new(ResponseBody)
				}
				(*out.ResponseBody).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet1(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix[1:])
		if in.Header == nil {
			out.RawString("null")
		} else {
			(*in.Header).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"request\":"
		out.RawString(prefix)
		if in.RequestBody == nil {
			out.RawString("null")
		} else {
			(*in.RequestBody).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"response\":"
		out.RawString(prefix)
		if in.ResponseBody == nil {
			out.RawString("null")
		} else {
			(*in.ResponseBody).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet1(l, v)
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet2(in *jlexer.Lexer, out *RequestHeader) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
				out.Header = nil
			} else {
				if out.Header == nil {
					out.Header = new(Header)
				}
				(*out.Header).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet2(out *jwriter.Writer, in RequestHeader) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Header != nil {
		const prefix string = ",\"header\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Header).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestHeader) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestHeader) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestHeader) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestHeader) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet2(l, v)
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet3(in *jlexer.Lexer, out *RequestBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				if out.Body == nil {
					out.Body = new(Body)
				}
				(*out.Body).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet3(out *jwriter.Writer, in RequestBody) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Body != nil {
		const prefix string = ",\"request\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Body).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet3(l, v)
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet4(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
				out.Header = nil
			} else {
				if out.Header == nil {
					out.Header = new(Header)
				}
				(*out.Header).UnmarshalEasyJSON(in)
			}
		case "request":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				if out.Body == nil {
					out.Body = new(Body)
				}
				(*out.Body).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet4(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Header != nil {
		const prefix string = ",\"header\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Header).MarshalEasyJSON(out)
	}
	if in.Body != nil {
		const prefix string = ",\"request\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Body).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet4(l, v)
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet5(in *jlexer.Lexer, out *Header) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "method":
			out.Method = string(in.String())
		case "token":
			out.Token = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet5(out *jwriter.Writer, in Header) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Header) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Header) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Header) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Header) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet5(l, v)
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet6(in *jlexer.Lexer, out *Data) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user":
			if in.IsNull() {
				in.Skip()
				out.User = nil
			} else {
				if out.User == nil {
					out.User = new(struct {
						Name string `json:"name,omitempty"`
						Guid string `json:"guid,omitempty"`
					})
				}
				easyjson6a975c40Decode(in, out.User)
			}
		case "operations":
			if in.IsNull() {
				in.Skip()
				out.Operations = nil
			} else {
				in.Delim('[')
				if out.Operations == nil {
					if !in.IsDelim(']') {
						out.Operations = make([]struct {
							OperationCode string `json:"code,omitempty"`
							OperationName string `json:"name,omitempty"`
						}, 0, 2)
					} else {
						out.Operations = []struct {
							OperationCode string `json:"code,omitempty"`
							OperationName string `json:"name,omitempty"`
						}{}
					}
				} else {
					out.Operations = (out.Operations)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						OperationCode string `json:"code,omitempty"`
						OperationName string `json:"name,omitempty"`
					}
					easyjson6a975c40Decode1(in, &v1)
					out.Operations = append(out.Operations, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "task":
			if in.IsNull() {
				in.Skip()
				out.Task = nil
			} else {
				if out.Task == nil {
					out.Task = new(struct {
						Taskname string `json:"taskname,omitempty"`
						Taskguid string `json:"taskguid,omitempty"`
						Totalqty string `json:"totalqty,omitempty"`
						Execqty  string `json:"execqty,omitempty"`
					})
				}
				easyjson6a975c40Decode2(in, out.Task)
			}
		case "tasklist":
			if in.IsNull() {
				in.Skip()
				out.Tasklist = nil
			} else {
				in.Delim('[')
				if out.Tasklist == nil {
					if !in.IsDelim(']') {
						out.Tasklist = make([]struct {
							Taskname string `json:"taskname,omitempty"`
							Taskguid string `json:"taskguid,omitempty"`
							Taskcode string `json:"taskcode,omitempty"`
						}, 0, 1)
					} else {
						out.Tasklist = []struct {
							Taskname string `json:"taskname,omitempty"`
							Taskguid string `json:"taskguid,omitempty"`
							Taskcode string `json:"taskcode,omitempty"`
						}{}
					}
				} else {
					out.Tasklist = (out.Tasklist)[:0]
				}
				for !in.IsDelim(']') {
					var v2 struct {
						Taskname string `json:"taskname,omitempty"`
						Taskguid string `json:"taskguid,omitempty"`
						Taskcode string `json:"taskcode,omitempty"`
					}
					easyjson6a975c40Decode3(in, &v2)
					out.Tasklist = append(out.Tasklist, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "caselist":
			if in.IsNull() {
				in.Skip()
				out.Caselist = nil
			} else {
				in.Delim('[')
				if out.Caselist == nil {
					if !in.IsDelim(']') {
						out.Caselist = make([]struct {
							Caseid    string `json:"caseid,omitempty"`
							Casename  string `json:"casename,omitempty"`
							Locid     string `json:"locid,omitempty"`
							Loc       string `json:"loc,omitempty"`
							Qty       int    `json:"qty,omitempty"`
							Deviation bool   `json:"deviation,omitempty"`
						}, 0, 0)
					} else {
						out.Caselist = []struct {
							Caseid    string `json:"caseid,omitempty"`
							Casename  string `json:"casename,omitempty"`
							Locid     string `json:"locid,omitempty"`
							Loc       string `json:"loc,omitempty"`
							Qty       int    `json:"qty,omitempty"`
							Deviation bool   `json:"deviation,omitempty"`
						}{}
					}
				} else {
					out.Caselist = (out.Caselist)[:0]
				}
				for !in.IsDelim(']') {
					var v3 struct {
						Caseid    string `json:"caseid,omitempty"`
						Casename  string `json:"casename,omitempty"`
						Locid     string `json:"locid,omitempty"`
						Loc       string `json:"loc,omitempty"`
						Qty       int    `json:"qty,omitempty"`
						Deviation bool   `json:"deviation,omitempty"`
					}
					easyjson6a975c40Decode4(in, &v3)
					out.Caselist = append(out.Caselist, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "case":
			if in.IsNull() {
				in.Skip()
				out.Case = nil
			} else {
				if out.Case == nil {
					out.Case = new(struct {
						Casename string `json:"casename,omitempty"`
						Caseid   string `json:"caseid,omitempty"`
					})
				}
				easyjson6a975c40Decode5(in, out.Case)
			}
		case "skucaselist":
			if in.IsNull() {
				in.Skip()
				out.Skucaselist = nil
			} else {
				in.Delim('[')
				if out.Skucaselist == nil {
					if !in.IsDelim(']') {
						out.Skucaselist = make([]struct {
							Skubarcode string `json:"skubarcode,omitempty"`
							Skuname    string `json:"skuname,omitempty"`
							Skuguid    string `json:"skuguid,omitempty"`
							RequiredKM bool   `json:"requiredKM,omitempty"`
							Qty        int    `json:"qty,omitempty"`
							Deviation  bool   `json:"deviation,omitempty"`
						}, 0, 0)
					} else {
						out.Skucaselist = []struct {
							Skubarcode string `json:"skubarcode,omitempty"`
							Skuname    string `json:"skuname,omitempty"`
							Skuguid    string `json:"skuguid,omitempty"`
							RequiredKM bool   `json:"requiredKM,omitempty"`
							Qty        int    `json:"qty,omitempty"`
							Deviation  bool   `json:"deviation,omitempty"`
						}{}
					}
				} else {
					out.Skucaselist = (out.Skucaselist)[:0]
				}
				for !in.IsDelim(']') {
					var v4 struct {
						Skubarcode string `json:"skubarcode,omitempty"`
						Skuname    string `json:"skuname,omitempty"`
						Skuguid    string `json:"skuguid,omitempty"`
						RequiredKM bool   `json:"requiredKM,omitempty"`
						Qty        int    `json:"qty,omitempty"`
						Deviation  bool   `json:"deviation,omitempty"`
					}
					easyjson6a975c40Decode6(in, &v4)
					out.Skucaselist = append(out.Skucaselist, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "skuguid":
			if in.IsNull() {
				in.Skip()
				out.Skuguid = nil
			} else {
				if out.Skuguid == nil {
					out.Skuguid = new(string)
				}
				*out.Skuguid = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet6(out *jwriter.Writer, in Data) {
	out.RawByte('{')
	first := true
	_ = first
	if in.User != nil {
		const prefix string = ",\"user\":"
		first = false
		out.RawString(prefix[1:])
		easyjson6a975c40Encode(out, *in.User)
	}
	if len(in.Operations) != 0 {
		const prefix string = ",\"operations\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Operations {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode1(out, v6)
			}
			out.RawByte(']')
		}
	}
	if in.Task != nil {
		const prefix string = ",\"task\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode2(out, *in.Task)
	}
	if len(in.Tasklist) != 0 {
		const prefix string = ",\"tasklist\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v7, v8 := range in.Tasklist {
				if v7 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode3(out, v8)
			}
			out.RawByte(']')
		}
	}
	if len(in.Caselist) != 0 {
		const prefix string = ",\"caselist\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v9, v10 := range in.Caselist {
				if v9 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode4(out, v10)
			}
			out.RawByte(']')
		}
	}
	if in.Case != nil {
		const prefix string = ",\"case\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode5(out, *in.Case)
	}
	if len(in.Skucaselist) != 0 {
		const prefix string = ",\"skucaselist\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.Skucaselist {
				if v11 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode6(out, v12)
			}
			out.RawByte(']')
		}
	}
	if in.Skuguid != nil {
		const prefix string = ",\"skuguid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Skuguid))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Data) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Data) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Data) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Data) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet6(l, v)
}
func easyjson6a975c40Decode6(in *jlexer.Lexer, out *struct {
	Skubarcode string `json:"skubarcode,omitempty"`
	Skuname    string `json:"skuname,omitempty"`
	Skuguid    string `json:"skuguid,omitempty"`
	RequiredKM bool   `json:"requiredKM,omitempty"`
	Qty        int    `json:"qty,omitempty"`
	Deviation  bool   `json:"deviation,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "skubarcode":
			out.Skubarcode = string(in.String())
		case "skuname":
			out.Skuname = string(in.String())
		case "skuguid":
			out.Skuguid = string(in.String())
		case "requiredKM":
			out.RequiredKM = bool(in.Bool())
		case "qty":
			out.Qty = int(in.Int())
		case "deviation":
			out.Deviation = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode6(out *jwriter.Writer, in struct {
	Skubarcode string `json:"skubarcode,omitempty"`
	Skuname    string `json:"skuname,omitempty"`
	Skuguid    string `json:"skuguid,omitempty"`
	RequiredKM bool   `json:"requiredKM,omitempty"`
	Qty        int    `json:"qty,omitempty"`
	Deviation  bool   `json:"deviation,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Skubarcode != "" {
		const prefix string = ",\"skubarcode\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Skubarcode))
	}
	if in.Skuname != "" {
		const prefix string = ",\"skuname\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Skuname))
	}
	if in.Skuguid != "" {
		const prefix string = ",\"skuguid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Skuguid))
	}
	if in.RequiredKM {
		const prefix string = ",\"requiredKM\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.RequiredKM))
	}
	if in.Qty != 0 {
		const prefix string = ",\"qty\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Qty))
	}
	if in.Deviation {
		const prefix string = ",\"deviation\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Deviation))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode5(in *jlexer.Lexer, out *struct {
	Casename string `json:"casename,omitempty"`
	Caseid   string `json:"caseid,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "casename":
			out.Casename = string(in.String())
		case "caseid":
			out.Caseid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode5(out *jwriter.Writer, in struct {
	Casename string `json:"casename,omitempty"`
	Caseid   string `json:"caseid,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Casename != "" {
		const prefix string = ",\"casename\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Casename))
	}
	if in.Caseid != "" {
		const prefix string = ",\"caseid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Caseid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode4(in *jlexer.Lexer, out *struct {
	Caseid    string `json:"caseid,omitempty"`
	Casename  string `json:"casename,omitempty"`
	Locid     string `json:"locid,omitempty"`
	Loc       string `json:"loc,omitempty"`
	Qty       int    `json:"qty,omitempty"`
	Deviation bool   `json:"deviation,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "caseid":
			out.Caseid = string(in.String())
		case "casename":
			out.Casename = string(in.String())
		case "locid":
			out.Locid = string(in.String())
		case "loc":
			out.Loc = string(in.String())
		case "qty":
			out.Qty = int(in.Int())
		case "deviation":
			out.Deviation = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode4(out *jwriter.Writer, in struct {
	Caseid    string `json:"caseid,omitempty"`
	Casename  string `json:"casename,omitempty"`
	Locid     string `json:"locid,omitempty"`
	Loc       string `json:"loc,omitempty"`
	Qty       int    `json:"qty,omitempty"`
	Deviation bool   `json:"deviation,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Caseid != "" {
		const prefix string = ",\"caseid\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Caseid))
	}
	if in.Casename != "" {
		const prefix string = ",\"casename\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Casename))
	}
	if in.Locid != "" {
		const prefix string = ",\"locid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Locid))
	}
	if in.Loc != "" {
		const prefix string = ",\"loc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Loc))
	}
	if in.Qty != 0 {
		const prefix string = ",\"qty\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Qty))
	}
	if in.Deviation {
		const prefix string = ",\"deviation\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Deviation))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode3(in *jlexer.Lexer, out *struct {
	Taskname string `json:"taskname,omitempty"`
	Taskguid string `json:"taskguid,omitempty"`
	Taskcode string `json:"taskcode,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "taskname":
			out.Taskname = string(in.String())
		case "taskguid":
			out.Taskguid = string(in.String())
		case "taskcode":
			out.Taskcode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode3(out *jwriter.Writer, in struct {
	Taskname string `json:"taskname,omitempty"`
	Taskguid string `json:"taskguid,omitempty"`
	Taskcode string `json:"taskcode,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Taskname != "" {
		const prefix string = ",\"taskname\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Taskname))
	}
	if in.Taskguid != "" {
		const prefix string = ",\"taskguid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Taskguid))
	}
	if in.Taskcode != "" {
		const prefix string = ",\"taskcode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Taskcode))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode2(in *jlexer.Lexer, out *struct {
	Taskname string `json:"taskname,omitempty"`
	Taskguid string `json:"taskguid,omitempty"`
	Totalqty string `json:"totalqty,omitempty"`
	Execqty  string `json:"execqty,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "taskname":
			out.Taskname = string(in.String())
		case "taskguid":
			out.Taskguid = string(in.String())
		case "totalqty":
			out.Totalqty = string(in.String())
		case "execqty":
			out.Execqty = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode2(out *jwriter.Writer, in struct {
	Taskname string `json:"taskname,omitempty"`
	Taskguid string `json:"taskguid,omitempty"`
	Totalqty string `json:"totalqty,omitempty"`
	Execqty  string `json:"execqty,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Taskname != "" {
		const prefix string = ",\"taskname\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Taskname))
	}
	if in.Taskguid != "" {
		const prefix string = ",\"taskguid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Taskguid))
	}
	if in.Totalqty != "" {
		const prefix string = ",\"totalqty\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Totalqty))
	}
	if in.Execqty != "" {
		const prefix string = ",\"execqty\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Execqty))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode1(in *jlexer.Lexer, out *struct {
	OperationCode string `json:"code,omitempty"`
	OperationName string `json:"name,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.OperationCode = string(in.String())
		case "name":
			out.OperationName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode1(out *jwriter.Writer, in struct {
	OperationCode string `json:"code,omitempty"`
	OperationName string `json:"name,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.OperationCode != "" {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.OperationCode))
	}
	if in.OperationName != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.OperationName))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode(in *jlexer.Lexer, out *struct {
	Name string `json:"name,omitempty"`
	Guid string `json:"guid,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "guid":
			out.Guid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode(out *jwriter.Writer, in struct {
	Name string `json:"name,omitempty"`
	Guid string `json:"guid,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Guid != "" {
		const prefix string = ",\"guid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Guid))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeFinnflareComDctBackendNet7(in *jlexer.Lexer, out *Body) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "barcode":
			if in.IsNull() {
				in.Skip()
				out.Barcode = nil
			} else {
				if out.Barcode == nil {
					out.Barcode = new(string)
				}
				*out.Barcode = string(in.String())
			}
		case "skubarcode":
			if in.IsNull() {
				in.Skip()
				out.SkuBarcode = nil
			} else {
				if out.SkuBarcode == nil {
					out.SkuBarcode = new(string)
				}
				*out.SkuBarcode = string(in.String())
			}
		case "user":
			if in.IsNull() {
				in.Skip()
				out.User = nil
			} else {
				if out.User == nil {
					out.User = new(struct {
						Guid *string `json:"guid,omitempty"`
					})
				}
				easyjson6a975c40Decode7(in, out.User)
			}
		case "operationcode":
			if in.IsNull() {
				in.Skip()
				out.OperationCode = nil
			} else {
				if out.OperationCode == nil {
					out.OperationCode = new(string)
				}
				*out.OperationCode = string(in.String())
			}
		case "task":
			if in.IsNull() {
				in.Skip()
				out.Task = nil
			} else {
				if out.Task == nil {
					out.Task = new(struct {
						Taskguid string `json:"taskguid"`
					})
				}
				easyjson6a975c40Decode8(in, out.Task)
			}
		case "case":
			if in.IsNull() {
				in.Skip()
				out.Case = nil
			} else {
				if out.Case == nil {
					out.Case = new(struct {
						Caseid string `json:"caseid"`
					})
				}
				easyjson6a975c40Decode9(in, out.Case)
			}
		case "previouscase":
			if in.IsNull() {
				in.Skip()
				out.Previouscase = nil
			} else {
				if out.Previouscase == nil {
					out.Previouscase = new(struct {
						Previouscaseid string `json:"previouscaseid"`
					})
				}
				easyjson6a975c40Decode10(in, out.Previouscase)
			}
		case "fromcase":
			if in.IsNull() {
				in.Skip()
				out.Fromcase = nil
			} else {
				if out.Fromcase == nil {
					out.Fromcase = new(struct {
						Fromcaseid string `json:"fromcaseid"`
					})
				}
				easyjson6a975c40Decode11(in, out.Fromcase)
			}
		case "fromloc":
			if in.IsNull() {
				in.Skip()
				out.Fromloc = nil
			} else {
				if out.Fromloc == nil {
					out.Fromloc = new(struct {
						Fromlocid string `json:"fromlocid"`
					})
				}
				easyjson6a975c40Decode12(in, out.Fromloc)
			}
		case "sku":
			if in.IsNull() {
				in.Skip()
				out.Sku = nil
			} else {
				if out.Sku == nil {
					out.Sku = new(struct {
						Skubarcode string `json:"skubarcode"`
					})
				}
				easyjson6a975c40Decode13(in, out.Sku)
			}
		case "tocase":
			if in.IsNull() {
				in.Skip()
				out.Tocase = nil
			} else {
				if out.Tocase == nil {
					out.Tocase = new(struct {
						Tocaseid string `json:"tocaseid"`
					})
				}
				easyjson6a975c40Decode14(in, out.Tocase)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeFinnflareComDctBackendNet7(out *jwriter.Writer, in Body) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Barcode != nil {
		const prefix string = ",\"barcode\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Barcode))
	}
	if in.SkuBarcode != nil {
		const prefix string = ",\"skubarcode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SkuBarcode))
	}
	if in.User != nil {
		const prefix string = ",\"user\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode7(out, *in.User)
	}
	if in.OperationCode != nil {
		const prefix string = ",\"operationcode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.OperationCode))
	}
	if in.Task != nil {
		const prefix string = ",\"task\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode8(out, *in.Task)
	}
	if in.Case != nil {
		const prefix string = ",\"case\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode9(out, *in.Case)
	}
	if in.Previouscase != nil {
		const prefix string = ",\"previouscase\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode10(out, *in.Previouscase)
	}
	if in.Fromcase != nil {
		const prefix string = ",\"fromcase\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode11(out, *in.Fromcase)
	}
	if in.Fromloc != nil {
		const prefix string = ",\"fromloc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode12(out, *in.Fromloc)
	}
	if in.Sku != nil {
		const prefix string = ",\"sku\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode13(out, *in.Sku)
	}
	if in.Tocase != nil {
		const prefix string = ",\"tocase\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson6a975c40Encode14(out, *in.Tocase)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Body) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeFinnflareComDctBackendNet7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Body) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeFinnflareComDctBackendNet7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Body) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeFinnflareComDctBackendNet7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Body) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeFinnflareComDctBackendNet7(l, v)
}
func easyjson6a975c40Decode14(in *jlexer.Lexer, out *struct {
	Tocaseid string `json:"tocaseid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tocaseid":
			out.Tocaseid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode14(out *jwriter.Writer, in struct {
	Tocaseid string `json:"tocaseid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tocaseid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Tocaseid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode13(in *jlexer.Lexer, out *struct {
	Skubarcode string `json:"skubarcode"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "skubarcode":
			out.Skubarcode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode13(out *jwriter.Writer, in struct {
	Skubarcode string `json:"skubarcode"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"skubarcode\":"
		out.RawString(prefix[1:])
		out.String(string(in.Skubarcode))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode12(in *jlexer.Lexer, out *struct {
	Fromlocid string `json:"fromlocid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fromlocid":
			out.Fromlocid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode12(out *jwriter.Writer, in struct {
	Fromlocid string `json:"fromlocid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fromlocid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Fromlocid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode11(in *jlexer.Lexer, out *struct {
	Fromcaseid string `json:"fromcaseid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fromcaseid":
			out.Fromcaseid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode11(out *jwriter.Writer, in struct {
	Fromcaseid string `json:"fromcaseid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fromcaseid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Fromcaseid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode10(in *jlexer.Lexer, out *struct {
	Previouscaseid string `json:"previouscaseid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "previouscaseid":
			out.Previouscaseid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode10(out *jwriter.Writer, in struct {
	Previouscaseid string `json:"previouscaseid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"previouscaseid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Previouscaseid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode9(in *jlexer.Lexer, out *struct {
	Caseid string `json:"caseid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "caseid":
			out.Caseid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode9(out *jwriter.Writer, in struct {
	Caseid string `json:"caseid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"caseid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Caseid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode8(in *jlexer.Lexer, out *struct {
	Taskguid string `json:"taskguid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "taskguid":
			out.Taskguid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode8(out *jwriter.Writer, in struct {
	Taskguid string `json:"taskguid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"taskguid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Taskguid))
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode7(in *jlexer.Lexer, out *struct {
	Guid *string `json:"guid,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "guid":
			if in.IsNull() {
				in.Skip()
				out.Guid = nil
			} else {
				if out.Guid == nil {
					out.Guid = new(string)
				}
				*out.Guid = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode7(out *jwriter.Writer, in struct {
	Guid *string `json:"guid,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Guid != nil {
		const prefix string = ",\"guid\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Guid))
	}
	out.RawByte('}')
}
